# DevBooks Embedding - Azure OpenAI 配置示例

enabled: true

api:
  # Azure OpenAI Embedding
  model: text-embedding-ada-002
  api_key: ${AZURE_OPENAI_KEY}

  # Azure 格式：https://{resource}.openai.azure.com/openai/deployments/{deployment}
  # 注意：需要在后面添加 /embeddings 会由脚本自动处理
  base_url: https://your-resource.openai.azure.com/openai/deployments/your-embedding-deployment

  timeout: 30
  batch_size: 50

vector_db:
  storage_path: .devbooks/embeddings/
  dimension: 1536
  index_type: flat

chunking:
  by_symbol: true
  max_chunk_tokens: 512
  overlap_tokens: 50
  include_comments: true
  include_imports: false

filters:
  include_extensions:
    - .ts
    - .tsx
    - .js
    - .jsx
    - .py
    - .cs
    - .java

  exclude_dirs:
    - node_modules
    - bin
    - obj
    - dist
    - build

search:
  top_k: 5
  similarity_threshold: 0.7
  include_snippet: true
  snippet_max_lines: 20

logging:
  level: INFO
  log_file: .devbooks/embeddings/embedding.log

performance:
  max_concurrent_requests: 5
  cache_size_mb: 100
  enable_compression: false
