# DevBooks Embedding API Configuration
# 向量化与语义搜索配置

# 是否启用 Embedding 功能
enabled: true

# API 配置
api:
  # 模型名称（支持 OpenAI 兼容接口）
  # 常见选项：
  #   - text-embedding-3-small (OpenAI, 1536维, 性价比高)
  #   - text-embedding-3-large (OpenAI, 3072维, 效果更好)
  #   - text-embedding-ada-002 (OpenAI 旧版本)
  #   - BAAI/bge-small-zh-v1.5 (本地模型)
  model: text-embedding-3-small

  # API 密钥
  # 支持三种方式：
  #   1. 直接填写: api_key: sk-xxx
  #   2. 环境变量引用: api_key: ${OPENAI_API_KEY}
  #   3. 留空，从环境变量 EMBEDDING_API_KEY 读取
  api_key: ${OPENAI_API_KEY}

  # API 基础地址
  # OpenAI: https://api.openai.com/v1
  # Azure OpenAI: https://your-resource.openai.azure.com
  # 本地服务: http://localhost:8000/v1
  base_url: https://api.openai.com/v1

  # 请求超时（秒）
  timeout: 30

  # 批处理大小（一次请求多少条文本）
  batch_size: 50

# 向量数据库配置
vector_db:
  # 存储路径（相对于项目根目录）
  storage_path: .devbooks/embeddings/

  # 向量维度（需与模型匹配）
  # text-embedding-3-small: 1536
  # text-embedding-3-large: 3072
  dimension: 1536

  # 索引类型：flat（精确搜索）/ hnsw（近似搜索，更快）
  index_type: flat

# 代码分块策略
chunking:
  # 是否按函数/类分块（推荐）
  by_symbol: true

  # 最大块大小（token数）
  max_chunk_tokens: 512

  # 块之间的重叠（token数）
  overlap_tokens: 50

  # 是否包含注释
  include_comments: true

  # 是否包含导入语句
  include_imports: false

# 文件过滤
filters:
  # 包含的文件扩展名
  include_extensions:
    - .ts
    - .tsx
    - .js
    - .jsx
    - .py
    - .go
    - .rs
    - .java
    - .md

  # 排除的目录
  exclude_dirs:
    - node_modules
    - dist
    - build
    - .git
    - __pycache__
    - venv
    - .venv
    - target
    - .next
    - .nuxt

  # 排除的文件模式
  exclude_patterns:
    - "*.test.ts"
    - "*.spec.ts"
    - "*.test.js"
    - "*.min.js"
    - "*.bundle.js"
    - "package-lock.json"
    - "yarn.lock"

# 增量更新策略
incremental:
  # 是否启用增量更新
  enabled: true

  # 检查间隔（秒）
  check_interval: 300

  # 基于文件修改时间判断是否需要重新向量化
  use_mtime: true

# 搜索配置
search:
  # 默认返回结果数
  top_k: 5

  # 相似度阈值（0-1，低于此值的结果会被过滤）
  similarity_threshold: 0.7

  # 是否在结果中包含代码片段
  include_snippet: true

  # 代码片段最大行数
  snippet_max_lines: 20

# 日志配置
logging:
  # 日志级别: DEBUG / INFO / WARN / ERROR
  level: INFO

  # 日志文件路径（相对于项目根目录）
  log_file: .devbooks/embeddings/embedding.log

# 性能调优
performance:
  # 并发请求数（向 API 发送请求时）
  max_concurrent_requests: 5

  # 本地缓存大小（MB）
  cache_size_mb: 100

  # 是否启用向量压缩（减少存储空间）
  enable_compression: false

# 实验性功能
experimental:
  # 是否使用本地模型（需要安装 sentence-transformers）
  use_local_model: false

  # 本地模型路径
  local_model_path: ""

  # 是否启用语义代码导航
  enable_semantic_nav: true

  # 是否启用智能代码推荐
  enable_code_suggestions: false
