# DevBooks 依赖卫士 GitHub Actions 模板
# 用途：在 PR 时自动运行架构合规检查，阻止违规合并
#
# 安装方式：
#   cp this-file .github/workflows/devbooks-guardrail.yml
#
# 前提条件：
#   1. 项目已接入 DevBooks（有 <truth-root>/architecture/）
#   2. SCIP 索引已生成（可选，用于更精确的依赖分析）

name: DevBooks Guardrail

on:
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'src/**'
      - 'lib/**'
      - 'app/**'
      - 'packages/**'
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.py'
      - '*.go'

env:
  # 配置项（按项目调整）
  TRUTH_ROOT: 'specs'           # 或 'openspec/specs'
  CHANGE_ROOT: 'changes'        # 或 'openspec/changes'
  COMPLEXITY_THRESHOLD: 15      # 圈复杂度阈值
  HOTSPOT_THRESHOLD: 10         # 热点变更次数阈值
  FAIL_ON_LAYER_VIOLATION: true # 分层违规是否阻止合并
  FAIL_ON_CYCLE: true           # 循环依赖是否阻止合并

jobs:
  guardrail:
    name: Architecture Guardrail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史用于热点分析

      - name: Setup Node.js (for TypeScript projects)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python (for Python projects)
        if: hashFiles('pyproject.toml', 'setup.py', 'requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install DevBooks Scripts
        run: |
          # 下载 DevBooks 护栏脚本
          mkdir -p .devbooks/scripts
          curl -sL https://raw.githubusercontent.com/your-org/dev-playbooks/main/skills/devbooks-delivery-workflow/scripts/guardrail-check.sh \
            -o .devbooks/scripts/guardrail-check.sh
          chmod +x .devbooks/scripts/guardrail-check.sh

      - name: Get Changed Files
        id: changed
        run: |
          # 获取本 PR 变更的文件
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | tr '\n' ' ')
          echo "files=$CHANGED" >> $GITHUB_OUTPUT
          echo "Changed files: $CHANGED"

      - name: Run Complexity Check
        id: complexity
        continue-on-error: true
        run: |
          echo "## Complexity Check" >> $GITHUB_STEP_SUMMARY

          # 使用 scc 或类似工具检查复杂度
          if command -v scc &> /dev/null; then
            scc --by-file --sort complexity ${{ steps.changed.outputs.files }} | tee complexity.txt

            # 检查是否超过阈值
            HIGH_COMPLEXITY=$(grep -E "^\s+[0-9]+\s+[0-9]+\s+($COMPLEXITY_THRESHOLD|[2-9][0-9]|[1-9][0-9]{2,})" complexity.txt | wc -l)
            if [ "$HIGH_COMPLEXITY" -gt 0 ]; then
              echo "::warning::发现 $HIGH_COMPLEXITY 个高复杂度文件（>$COMPLEXITY_THRESHOLD）"
              echo "⚠️ 发现 $HIGH_COMPLEXITY 个高复杂度文件" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "scc 未安装，跳过复杂度检查" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run Hotspot Check
        id: hotspot
        continue-on-error: true
        run: |
          echo "## Hotspot Check" >> $GITHUB_STEP_SUMMARY

          # 检查变更的文件是否是热点
          for file in ${{ steps.changed.outputs.files }}; do
            if [ -f "$file" ]; then
              CHANGE_COUNT=$(git log --since="30 days ago" --oneline -- "$file" | wc -l)
              if [ "$CHANGE_COUNT" -gt "$HOTSPOT_THRESHOLD" ]; then
                echo "::warning file=$file::热点文件：$file 在30天内被修改 $CHANGE_COUNT 次"
                echo "⚠️ 热点文件: \`$file\` ($CHANGE_COUNT 次变更)" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          done

      - name: Run Layer Violation Check
        id: layers
        if: env.FAIL_ON_LAYER_VIOLATION == 'true'
        run: |
          echo "## Layer Violation Check" >> $GITHUB_STEP_SUMMARY

          # 检查分层约束（如果存在配置）
          LAYER_CONFIG="$TRUTH_ROOT/architecture/layers.yaml"
          if [ -f "$LAYER_CONFIG" ]; then
            # 简单的分层检查：检查是否有 domain 导入 infrastructure
            VIOLATIONS=""

            for file in ${{ steps.changed.outputs.files }}; do
              if [[ "$file" == *"/domain/"* ]]; then
                # domain 层不应该导入 infrastructure
                if grep -E "from.*infrastructure|import.*infrastructure" "$file" 2>/dev/null; then
                  VIOLATIONS="$VIOLATIONS\n- $file: domain 层导入了 infrastructure"
                fi
              fi
            done

            if [ -n "$VIOLATIONS" ]; then
              echo "::error::分层违规:$VIOLATIONS"
              echo "❌ 分层违规:$VIOLATIONS" >> $GITHUB_STEP_SUMMARY
              exit 1
            else
              echo "✅ 无分层违规" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "未配置分层约束，跳过检查" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Run Cycle Detection
        id: cycles
        if: env.FAIL_ON_CYCLE == 'true'
        run: |
          echo "## Cycle Detection" >> $GITHUB_STEP_SUMMARY

          # 如果有 madge 可以检测循环依赖
          if [ -f "package.json" ] && command -v npx &> /dev/null; then
            npx madge --circular src/ 2>/dev/null | tee cycles.txt || true

            if grep -q "Circular" cycles.txt; then
              echo "::error::检测到循环依赖"
              cat cycles.txt >> $GITHUB_STEP_SUMMARY
              exit 1
            else
              echo "✅ 无循环依赖" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "跳过循环依赖检查（非 Node.js 项目或 madge 未安装）" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Generate Summary
        if: always()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "## 检查结果" >> $GITHUB_STEP_SUMMARY
          echo "| 检查项 | 状态 |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|------|" >> $GITHUB_STEP_SUMMARY
          echo "| 复杂度检查 | ${{ steps.complexity.outcome == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 热点检查 | ${{ steps.hotspot.outcome == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 分层违规 | ${{ steps.layers.outcome == 'success' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 循环依赖 | ${{ steps.cycles.outcome == 'success' && '✅' || '❌' }} |" >> $GITHUB_STEP_SUMMARY

  # 可选：SCIP 索引更新
  update-index:
    name: Update SCIP Index
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SCIP Indexer
        run: |
          if [ -f "package.json" ]; then
            npm install -g @sourcegraph/scip-typescript
          fi

      - name: Generate SCIP Index
        run: |
          if [ -f "package.json" ]; then
            scip-typescript index --output index.scip
          fi

      - name: Upload Index Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scip-index
          path: index.scip
          retention-days: 7
