# CI 工作流模板
# 借鉴 VS Code 的 .github/workflows/ 结构
# 使用方式：复制到项目的 .github/workflows/ 目录

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# 取消同一 PR 的重复运行
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # ============================================
  # 阶段 1：快速检查（< 2 分钟）
  # ============================================
  hygiene:
    name: Hygiene Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for debug statements
        run: |
          if grep -rE 'console\.(log|debug)|debugger' src/ --include="*.ts" --include="*.js" 2>/dev/null; then
            echo "::error::Found debug statements in source code"
            exit 1
          fi
          echo "No debug statements found"

      - name: Check for test.only
        run: |
          if grep -rE '\.only\s*\(' tests/ --include="*.ts" --include="*.js" 2>/dev/null; then
            echo "::error::Found .only() in tests"
            exit 1
          fi
          echo "No .only() found"

      - name: Check for @ts-ignore
        run: |
          count=$(grep -rE '@ts-ignore' src/ --include="*.ts" 2>/dev/null | wc -l || echo 0)
          if [ "$count" -gt 0 ]; then
            echo "::warning::Found $count @ts-ignore directives"
          fi

  # ============================================
  # 阶段 2：构建与类型检查
  # ============================================
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: hygiene
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run compile

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      # 缓存构建产物供后续 job 使用
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 1

  # ============================================
  # 阶段 3：测试
  # ============================================
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          flags: unit
        continue-on-error: true

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/

      - name: Run integration tests
        run: npm run test:integration

  # ============================================
  # 阶段 4：依赖安全检查
  # ============================================
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: hygiene
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Audit dependencies
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Check for known vulnerabilities
        run: npx snyk test --severity-threshold=high
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  # ============================================
  # 阶段 5：循环依赖检查
  # ============================================
  architecture:
    name: Architecture Check
    runs-on: ubuntu-latest
    needs: hygiene
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check circular dependencies
        run: |
          npx madge --circular src/ && echo "No circular dependencies found" || exit 1

  # ============================================
  # 最终门禁
  # ============================================
  gate:
    name: Gate
    runs-on: ubuntu-latest
    needs: [build, test-unit, test-integration, security, architecture]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
            echo "::error::Build failed"
            exit 1
          fi
          if [ "${{ needs.test-unit.result }}" != "success" ]; then
            echo "::error::Unit tests failed"
            exit 1
          fi
          if [ "${{ needs.test-integration.result }}" != "success" ]; then
            echo "::error::Integration tests failed"
            exit 1
          fi
          echo "All checks passed!"
